### ISSUE TITLE
Move Scribunto and Flow into LocalSettings.php

### ISSUE THREAD

**Issue by danyill** [danyill/compose-mediawiki-ubuntu#3]
The update / rebuildall scripts don't work when this is in the Docker php file

**Comment by danyill** [comment]
```
[89836fd6a82e78635f09d917] [no req]   MWUnknownContentModelException from line 347 of /var/www/html/w/includes/content/ContentHandler.php: The content model 'Scribunto' is not registered on this wiki.
See https://www.mediawiki.org/wiki/Content_handlers to find out which extensions handle this content model.
Backtrace:
#0 /var/www/html/w/includes/content/ContentHandler.php(284): ContentHandler::getForModelID(string)
#1 /var/www/html/w/includes/Title.php(4722): ContentHandler::getForTitle(Title)
#2 /var/www/html/w/includes/parser/Parser.php(877): Title->getPageLanguage()
#3 /var/www/html/w/includes/parser/Parser.php(2121): Parser->getTargetLanguage()
#4 /var/www/html/w/includes/parser/Parser.php(2086): Parser->replaceInternalLinks2(string)
#5 /var/www/html/w/includes/parser/Parser.php(1303): Parser->replaceInternalLinks(string)
#6 /var/www/html/w/includes/parser/Parser.php(447): Parser->internalParse(string)
#7 /var/www/html/w/includes/content/WikitextContent.php(330): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#8 /var/www/html/w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#9 /var/www/html/w/includes/content/AbstractContent.php(230): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#10 /var/www/html/w/maintenance/refreshLinks.php(264): AbstractContent->getSecondaryDataUpdates(Title)
#11 /var/www/html/w/maintenance/refreshLinks.php(186): RefreshLinks::fixLinksFromArticle(integer, boolean)
#12 /var/www/html/w/maintenance/refreshLinks.php(68): RefreshLinks->doRefreshLinks(integer, boolean, string, boolean, boolean)
#13 /var/www/html/w/maintenance/rebuildall.php(60): RefreshLinks->execute()
#14 /var/www/html/w/maintenance/doMaintenance.php(111): RebuildAll->execute()
#15 /var/www/html/w/maintenance/rebuildall.php(67): require_once(string)
#16 {main}
```
Fixed when in LocalSettings.php

```
[edb4b0f195257d9bb1030e42] [no req]   MWUnknownContentModelException from line 347 of /var/www/html/w/includes/content/ContentHandler.php: The content model 'flow-board' is not registered on this wiki.
See https://www.mediawiki.org/wiki/Content_handlers to find out which extensions handle this content model.
Backtrace:
#0 /var/www/html/w/includes/content/ContentHandler.php(284): ContentHandler::getForModelID(string)
#1 /var/www/html/w/includes/Title.php(4722): ContentHandler::getForTitle(Title)
#2 /var/www/html/w/includes/parser/Parser.php(877): Title->getPageLanguage()
#3 /var/www/html/w/includes/parser/Parser.php(2121): Parser->getTargetLanguage()
#4 /var/www/html/w/includes/parser/Parser.php(2086): Parser->replaceInternalLinks2(string)
#5 /var/www/html/w/includes/parser/Parser.php(1303): Parser->replaceInternalLinks(string)
#6 /var/www/html/w/includes/parser/Parser.php(447): Parser->internalParse(string)
#7 /var/www/html/w/includes/content/WikitextContent.php(330): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#8 /var/www/html/w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#9 /var/www/html/w/includes/content/AbstractContent.php(230): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#10 /var/www/html/w/maintenance/refreshLinks.php(264): AbstractContent->getSecondaryDataUpdates(Title)
#11 /var/www/html/w/maintenance/refreshLinks.php(186): RefreshLinks::fixLinksFromArticle(integer, boolean)
#12 /var/www/html/w/maintenance/refreshLinks.php(68): RefreshLinks->doRefreshLinks(integer, boolean, string, boolean, boolean)
#13 /var/www/html/w/maintenance/rebuildall.php(60): RefreshLinks->execute()
#14 /var/www/html/w/maintenance/doMaintenance.php(111): RebuildAll->execute()
#15 /var/www/html/w/maintenance/rebuildall.php(67): require_once(string)
#16 {main}
```
Completes successfully when I move the following lines to `LocalSettings.php`, run `maintenance/update.php` and then `maintenance/rebuildall.php`

```
# End of automatically generated settings.
# Add more configuration options below.

$wgShowExceptionDetails = true;


require_once "$IP/extensions/Scribunto/Scribunto.php";
$wgScribuntoDefaultEngine = 'luastandalone';

require_once "$IP/extensions/Flow/Flow.php"; // REL1_29+ wfLoadExtension( 'Flow' );
$wgFlowContentFormat = 'html';
$wgFlowSearchServers = [ 'elasticsearch' ];
$wgNamespaceContentModels[NS_TALK] = 'flow-board';
$wgNamespaceContentModels[NS_USER_TALK] = 'flow-board';

@include('DockerSettings.php');
```

**Comment by danyill** [comment]
Must check to see if I can just use the populateContentModel script for this.
